<template>
  <section class="panel comparison-export" aria-label="Export measurements">
    <div class="panel-head">
      <div><h2>Export records</h2><p>Export the open record or combine checked runs.</p></div>
      <span class="trace-badge">{{ records.length }}/{{ limit }}</span>
    </div>
    <div class="panel-body">
      <p class="comparison-note">SVG creates a paper-style grouped Vt, Vc and Vc/Vt table above the waveform chart. CSV opens in Excel; JSON preserves selected local data. ZIP is generated by the backend from its persisted analysis.</p>
      <div class="export-grid">
        <label><span>Export range</span><select v-model="scope"><option value="current">Current record</option><option value="comparison" :disabled="records.length < 2">Checked comparison · {{ records.length }}</option></select></label>
        <label><span>Waveform</span><select v-model="source" :disabled="format === 'zip'"><option value="offline">Backend · offline (default)</option><option value="realtime">Frontend · realtime</option></select></label>
        <label><span>Format</span><select v-model="format"><option value="svg">SVG report</option><option value="csv">CSV data</option><option value="json">JSON archive</option><option value="zip">Backend reproducible ZIP</option></select></label>
        <button class="btn btn-primary export-button" type="button" :disabled="!canExport || busy" @click="save"><PhDownloadSimple :size="18"/>{{ busy ? 'Preparing…' : 'Export' }}</button>
      </div>
      <p class="source-note">{{ sourceNote }}</p>
      <p class="panel-note" role="status">{{ message }}</p>
    </div>
  </section>
</template>

<script setup>
import { computed, ref, watch } from 'vue';
import { PhDownloadSimple } from '@phosphor-icons/vue';
import { downloadAnalysis, downloadComparison } from '../features/records/exportAnalysis.js';
import { downloadBackendAnalysisExport, downloadBackendComparisonExport } from '../features/offline/api.js';

const props = defineProps({ currentRecord: Object, records: { type: Array, default: () => [] }, limit: { type: Number, default: 8 } });
const message = ref('');
const scope = ref('current');
const format = ref('svg');
const source = ref('offline');
const busy = ref(false);
const targets = computed(() => scope.value === 'comparison' ? props.records : [props.currentRecord].filter(Boolean));
const backendReady = computed(() => targets.value.length >= (scope.value === 'comparison' ? 2 : 1) && targets.value.every(record => (
  record?.backendAnalysisId && (record?.backendStatus === 'complete' || record?.offline?.status === 'complete')
)));
const canExport = computed(() => format.value === 'zip' ? backendReady.value : (scope.value === 'comparison' ? props.records.length >= 2 : Boolean(props.currentRecord)));
const sourceNote = computed(() => {
  if (format.value === 'zip') return backendReady.value
    ? 'Backend ZIP includes reproducible JSON, Excel-readable CSV and SVG; videos and evidence images remain excluded.'
    : 'Run offline analysis successfully for every selected record to enable backend ZIP export.';
  return source.value === 'offline'
    ? 'Uses the backend-processed waveform. Records without offline analysis remain clearly marked as unavailable.'
    : 'Uses the frontend waveform saved during live measurement.';
});
watch(() => props.records.length, count => {
  if (count >= 2) scope.value = 'comparison';
  else if (scope.value === 'comparison') scope.value = 'current';
});
async function save() {
  if (busy.value) return;
  busy.value = true;
  try {
    const options = { source: source.value };
    if (format.value === 'zip') {
      if (scope.value === 'comparison') await downloadBackendComparisonExport(props.records);
      else await downloadBackendAnalysisExport(props.currentRecord?.backendAnalysisId);
    } else if (scope.value === 'comparison') downloadComparison(props.records, format.value, options);
    else downloadAnalysis(props.currentRecord, format.value, options);
    const label = scope.value === 'comparison' ? `${props.records.length}-run comparison` : 'current record';
    message.value = format.value === 'zip'
      ? `${label} backend ZIP requested.`
      : `${label} ${format.value.toUpperCase()} requested with ${source.value === 'offline' ? 'backend' : 'frontend'} waveform.`;
  } catch (error) {
    message.value = `Export failed: ${error.message}`;
  } finally {
    busy.value = false;
  }
}
</script>

<style scoped>
.comparison-export .panel-body { padding-top: 14px; }
.comparison-note { margin: 0 0 12px; color: var(--ink-soft); font-size: 13px; line-height: 1.55; }
.export-grid { display:grid; grid-template-columns:1fr; align-items:end; gap:9px; }
.export-grid label { display:grid; gap:4px; color:var(--ink-soft); font-size:12px; }
.export-grid select { min-width:0; min-height:38px; padding:7px 28px 7px 9px; border:1px solid var(--rule-strong); border-radius:var(--radius); background:var(--panel); color:var(--ink); }
.export-button { width:100%; justify-content:center; margin-top:2px; }
.source-note { margin:10px 0 0; color:var(--ink-faint); font-size:11px; line-height:1.45; }
@media (max-width: 760px) { .export-grid { grid-template-columns:1fr; } }
</style>
