import assert from 'node:assert/strict';
import { analysisCsv, analysisJson, analysisSvg, comparisonCsv, comparisonJson, comparisonRows, comparisonSvg, traceRows } from '../src/features/records/exportAnalysis.js';
const record={id:'<test>',samples:[{elapsedMs:0,areaPx:5},{elapsedMs:100,areaPx:6},{elapsedMs:200,areaPx:7}],
  realtime:{vcPx:null,vtPx:2,ratio:null,diagnostic:{vcPx:4},invalidReasons:['=UNSAFE'],qualityStatus:'review_required'},
  captureRoi:{phase_windows:{tidal:[0,1]}},videoBlob:new Blob(['private video']),evidence:[{imageUrl:'data:image/png;base64,xxx'}]};
const exported=JSON.parse(analysisJson(record));
assert.equal(exported.record.realtime.vcPx,null);
assert.equal(exported.record.realtime.diagnostic.vcPx,4);
assert.equal(exported.record.videoBlob.omitted_blob,true);
assert.ok(!analysisJson(record).includes('base64,xxx'));
assert.ok(analysisCsv(record).startsWith('\uFEFF'));
assert.ok(analysisCsv(record).includes("'=UNSAFE"));
assert.ok(analysisCsv(record,{source:'realtime'}).includes('exhale_trough'));
assert.ok(JSON.parse(analysisJson(record,{source:'realtime'})).waveform_landmarks.exhale_trough);
assert.equal(traceRows(record).filter(r=>r.series==='realtime_raw').length,3);
assert.ok(traceRows(record).every(r=>r.phase==='tidal'));
assert.ok(analysisSvg(record).includes('&lt;test&gt;'));
assert.ok(analysisSvg(record,{source:'realtime'}).includes('Respiratory movement waveform and metrics'));
assert.ok(analysisSvg(record,{source:'realtime'}).includes('Frontend / realtime'));
assert.ok(analysisSvg(record,{source:'realtime'}).includes('Backend / offline'));
assert.ok(analysisSvg(record,{source:'realtime'}).includes('Vt (px)'));
assert.ok(analysisSvg(record).includes('No data available'));
assert.doesNotThrow(()=>analysisSvg({}));
const second={...record,id:'second',title:'Morning run',note:'dark shirt',createdAt:'2026-09-09T01:02:03Z',realtime:{...record.realtime,ratio:4},offline:{ratio:5,vc_px:500,vt_px:100,quality:{status:'checks_passed'},timestamps_ms:[0,100,200],waveform:[10,20,15]}};
const third={...second,id:'third',createdAt:'2026-09-09T01:03:03Z',offline:{...second.offline,ratio:null,quality:{status:'review_required'},waveform:[2,4,3]}};
const phased={...second,id:'phased',captureRoi:{phase_windows:{maxInhale:[.05,.15],maxExhale:[.15,.25]}},offline:{...second.offline,timestamps_ms:[0,100,200,300],waveform:[1,10,5,0],diagnostic:{landmarks:{maxInhale:{ms:100},maxExhale:{ms:200}}}}};
const phaseOnly={...phased,id:'phase-only',offline:{...phased.offline,diagnostic:{}}};
const staleLandmark={...phased,id:'stale-landmark',offline:{...phased.offline,diagnostic:{landmarks:{maxInhale:{ms:0},maxExhale:{ms:300}}}}};
const missingPhaseFrames={...phased,id:'missing-phase-frames',captureRoi:{phase_windows:{maxInhale:[10,12],maxExhale:[30,32]}}};
assert.equal(comparisonRows([second,third]).length,2);
assert.equal(comparisonRows([second])[0].difference_percent,25);
assert.equal(comparisonRows([second])[0].realtime_vt_px,2);
assert.equal(comparisonRows([second])[0].realtime_vc_px,null);
assert.equal(comparisonRows([second])[0].offline_vt_px,100);
assert.equal(comparisonRows([second])[0].offline_vc_px,500);
assert.equal(comparisonRows([second])[0].label,'Morning run');
assert.equal(comparisonRows([second])[0].note,'dark shirt');
assert.equal(comparisonRows([second])[0].series,'offline_processed');
assert.equal(comparisonRows([second])[0].peak.time_ms,100);
assert.equal(comparisonRows([second])[0].trough.time_ms,0);
assert.equal(comparisonRows([phased])[0].peak.time_ms,100);
assert.equal(comparisonRows([phased])[0].trough.time_ms,200);
assert.equal(comparisonRows([phaseOnly])[0].peak.time_ms,100);
assert.equal(comparisonRows([phaseOnly])[0].trough.time_ms,200);
assert.equal(comparisonRows([staleLandmark])[0].peak.time_ms,100);
assert.equal(comparisonRows([staleLandmark])[0].trough.time_ms,200);
assert.equal(comparisonRows([missingPhaseFrames])[0].peak,null);
assert.equal(comparisonRows([missingPhaseFrames])[0].trough,null);
assert.equal(comparisonRows([second],{source:'realtime'})[0].series,'realtime_review_v3');
assert.equal(comparisonRows([third])[0].offline_ratio,null);
assert.ok(comparisonCsv([second,third]).startsWith('\uFEFF'));
assert.ok(comparisonCsv([second,third]).includes('normalized_trace'));
assert.ok(comparisonCsv([second]).includes('exhale_trough_time_ms'));
assert.ok(comparisonCsv([second]).includes('realtime_vt_px'));
assert.ok(comparisonCsv([second]).includes('offline_vc_px'));
assert.ok(comparisonCsv([second]).includes('dark shirt'));
assert.equal(JSON.parse(comparisonJson([second,third])).summary[1].offline_ratio,null);
assert.equal(JSON.parse(comparisonJson([phased])).normalized_traces[0].exhale_trough.time_ms,200);
const comparison= comparisonSvg([second,third]);
assert.ok(comparison.includes('Repeated-measurement Vc/Vt comparison'));
assert.ok(comparison.includes('Difference compares backend with frontend'));
assert.ok(comparison.includes('Frontend / realtime'));
assert.ok(comparison.includes('Backend / offline'));
assert.ok(comparison.includes('Vt (px)'));
assert.ok(comparison.includes('Vc (px)'));
assert.ok(comparison.includes('Elapsed recording time (seconds)'));
assert.ok(comparison.includes('Normalized shape within each run (0–1)'));
assert.ok(comparison.includes('Inhale peaks'));
assert.ok(comparison.includes('Exhale troughs'));
assert.ok(comparison.includes('R1 · 0.1 s'));
assert.ok(comparison.includes('R1 · 0.0 s'));
assert.ok(comparison.includes('Normal breathing'));
assert.ok(comparison.match(/<polyline/g).length>=2);
const realtimeComparison=comparisonSvg([second],{source:'realtime'});
assert.ok(realtimeComparison.includes('Waveform source: Frontend / realtime'));
assert.ok(realtimeComparison.includes('Run 1 · Frontend / realtime'));
assert.ok(analysisCsv(record,{source:'realtime'}).includes('realtime_review_v3'));
assert.ok(!analysisCsv(record,{source:'offline'}).includes('realtime_review_v3'));
assert.ok(analysisSvg(record,{source:'realtime'}).includes('Waveform peak'));
assert.ok(analysisSvg(record,{source:'realtime'}).includes('Waveform trough'));
assert.ok(analysisSvg(record,{source:'realtime'}).includes('Normal breathing'));
console.log('analysis export tests passed');
